# Site settings
title: Alexandre Faria - Software Engineer
description: About me description
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alexandre Faria
user_description: "Blablabla Java, Golang, docker? API, oauth2/openid, open source contributions."
user_title: Software Engineer
email: contact@alexandrefaria.net
twitter_username: al3xandre_faria
medium_username: alexandre.faria
github_username: lusoalex
linkedin_username: fariaalexandre

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
