# Site settings
title: Alexandre Faria - Software Engineer
description: About me description
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alexandre Faria
user_description: "Software Engineer since 2005, I am currently working for <a target=\"_blank\" href=\"https://www.decathlon-united.com\">Decathlon</a> group.
As a developer, I am more interested in the back side, especially on APIs and authentication/security topics. Sharing knowledge is what I prefer in my daily job.
Open source world is also a fascinating topic for me."
user_title: Software Engineer
email: contact@alexandrefaria.net
blog_username: lusoalex
github_username: lusoalex
twitter_username: lusoalex_
linkedin_username: fariaalexandre
medium_username: alexandre.faria
slideshare_username: AlexandreFaria11

# Google-analytics
google-analytics:
  id: "UA-133442797-1"

exclude: ['package.json', 'src' , 'node_modules']
